### ISSUE TITLE
(Bug) 3.0 breaks world loading and crashes the game

### ISSUE THREAD

**Issue by vinnyg0621** [everloste/my-mc-projects#3]
**Mod version**
3.1.0

**Describe the bug**
when I create a new world or an existing world loads a new chunk, the game just crashes. but I think it is your mod.

**To Reproduce (optional)**
1. create a new world
2. or go into a new chunk in an existing world

**Additional context (optional)**
[crash-2024-07-31_21.23.38-client.txt](https://github.com/user-attachments/files/16451826/crash-2024-07-31_21.23.38-client.txt)
[crash-2024-07-31_21.06.14-server.txt](https://github.com/user-attachments/files/16451836/crash-2024-07-31_21.06.14-server.txt)

(server on an existing world, and client on creating a new world.)

Thank you!

**Comment by vinnyg0621** [comment]
yeah, it's definitely this mod. after downgrading from 3.0 to 2.4.3 the world loads correctly.

**Comment by vinnyg0621** [comment]
and the crash detected that `minecraft:worldgen/placed_feature/ore_diamond_medium` was removed

**Comment by everloste** [comment]
so, the `ore_diamond_medium` feature is a menace in that it was added in 1.20.2 - any references to it in 1.20.1 will therefore crash the game. 
geophilic 2.4 'solved' this problem by simply including the feature itself, but as that is bad practice, geophilic 3 now takes this into account and references the feature only in 1.20.2 and above.

i cannot reproduce your issue in a vanilla-ish environment. it seems to me the issue is a different mod referencing that feature... and the reason 2.4.3 works is because it unintentionally patches it.

make sure you remove all instances of geophilic 2.4.3 before installing 3.0. if you so wish, a very easy fix is to create a datapack that has `minecraft:worldgen/placed_feature/ore_diamond_medium` in it.

but as far geophilic is concerned, upgrading from 2.4.3 to 3.1.0 works without a hitch in a vanilla environment. i would not push out a major update that didn't work ;p

lmk if my suggested fix worked.

ps: you have both classic geophilic and geophilic reforged installed, which i recommend against...

**Comment by everloste** [comment]
i will reopen this issue if it turns out i'm stupid

**Comment by vinnyg0621** [comment]
and I use this mod and the reforged because I have modded biomes.

**Comment by vinnyg0621** [comment]
wait, it might be biomes o plenty causing it

**Comment by vinnyg0621** [comment]
okay i added "diamond_ore_medium" in placed feature **and** configured feature into the minecraft folder. the world loaded, thanks!
